
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_apedrosa' # <-- Name of the project.
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

packages-install-path: packages

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  'dbt_date:time_zone': 'America/Sao_Paulo'


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_apedrosa:
    staging:
      +materialized: view
      +schema: stg
    marts:
      +materialized: table
      +schema: marts
    utils:
      +materialized: table
      +schema: sap_adw
    intermediate:
      +materialized: view
      +schema: intermediate
      
snapshots:
  +target_schema: dbt_apedrosa_history

seeds:
  dbt_apedrosa: # <-- Name of the project. If you renamed your project you have to change this as well
    sap_adventure_works:
      +schema: sap_adw